### ISSUE TITLE
exFAT directory issue

### ISSUE THREAD

**Issue by WMXZ-EU** [greiman/SdFs#4]
the following example (on teensy3.2) does not work with exFAT formatted disks (PC formatted)
but it works with FAT32

observation:
directories created seems to be corrupt and do not allow file to be created inside or to be opened in PC

best,
Walter

#include "SdFs.h"

#include <time.h>
#define EPOCH_YEAR 1970 //T3 RTC
#define LEAP_YEAR(Y) (((EPOCH_YEAR+Y)>0) && !((EPOCH_YEAR+Y)%4) && ( ((EPOCH_YEAR+Y)%100) || !((EPOCH_YEAR+Y)%400) ) )
static  const uint8_t monthDays[]={31,28,31,30,31,30,31,31,30,31,30,31}; 

/*  int  tm_sec;
  int tm_min;
  int tm_hour;
  int tm_mday;
  int tm_mon;
  int tm_year;
  int tm_wday;
  int tm_yday;
  int tm_isdst;
*/

struct tm seconds2tm(uint32_t tt)
{ struct tm tx;
  tx.tm_sec   = tt % 60;    tt /= 60; // now it is minutes
  tx.tm_min   = tt % 60;    tt /= 60; // now it is hours
  tx.tm_hour  = tt % 24;    tt /= 24; // now it is days
  tx.tm_wday  = ((tt + 4) % 7) + 1;   // Sunday is day 1 (tbv)

  // tt is now days since EPOCH_Year (1970)
  uint32_t year = 0;  
  uint32_t days = 0;
  while((unsigned)(days += (LEAP_YEAR(year) ? 366 : 365)) <= tt) year++;

  tx.tm_year = 1970+year; // year is offset from 1970 

  // correct for last (actual) year
  days -= (LEAP_YEAR(year) ? 366 : 365);
  tt  -= days; // now tt is days in this year, starting at 0
  
  uint32_t month=0;
  uint32_t monthLength=0;
  for (month=0; month<12; month++) 
  { monthLength = monthDays[month];
    if ((month==1) & LEAP_YEAR(year)) monthLength++; 
    if (tt<monthLength) break;
    tt -= monthLength;
  }
  tx.tm_mon = month + 1;   // jan is month 1  
  tx.tm_mday = tt + 1;     // day of month
  return tx;
}

void dateTime(uint16_t* date, uint16_t* time) {

  struct tm tx=seconds2tm(RTC_TSR);
    
  // Return date using FS_DATE macro to format fields.
  *date = FS_DATE(tx.tm_year, tx.tm_mon, tx.tm_mday);

  // Return time using FS_TIME macro to format fields.
  *time = FS_TIME(tx.tm_hour, tx.tm_min, tx.tm_sec);
}

/*********************************************************************/
  SdFs sd;
  FsFile root;
  FsFile file;

  #define SD_CS 10
  #define SD_CONFIG SdSpiConfig(SD_CS, DEDICATED_SPI, SPI_FULL_SPEED)

void setup() {
  // put your setup code here, to run once:

   while(!Serial);
   Serial.println("start");

   SPI.setMOSI(7);
   SPI.setSCK(14);
  
   if (!sd.begin(SD_CONFIG)) sd.errorHalt("sd.begin failed");
  
   // Set Time callback
   FsDateTime::callback = dateTime;

   sd.ls("/", LS_R);
   char dirname[80]="folder1";
    
    if(sd.exists(dirname)) 
      if(!sd.rmdir(dirname))sd.errorHalt("sd.rmdir failed");
    
    if(!sd.mkdir(dirname))sd.errorHalt("sd.mkdir failed");
    if(!sd.chdir(dirname))sd.errorHalt("sd.chdir failed");

   sd.ls("/", LS_R);
   

    char filename[80]="file.dat";
    if (!file.open(filename, O_CREAT | O_TRUNC |O_RDWR)) 
      sd.errorHalt("file.open failed");

    int nbuf=512;
    static uint8_t buffer[512];
    if (nbuf != file.write(buffer, nbuf)) sd.errorHalt("write failed");
      
    file.truncate();
    file.close();
    Serial.println("end");
}

void loop() {
  // put your main code here, to run repeatedly:

}

**Comment by WMXZ-EU** [comment]
it seams that SdFs with
#define SD_FS_DATE 20170815

has not this issue, but only later versions

**Comment by greiman** [comment]
Somehow a line was deleted when I modified the preceding line.

Here is a [link ](https://github.com/greiman/SdFs/commit/c8c9ea6d99bc0bab38515dfa5c5cddd6ee87047c)to the mod.

Try your example now.

**Comment by WMXZ-EU** [comment]
Works now.
