### ISSUE TITLE
 SD_CARD_ERROR_CMD58 = 0x12 , but arduino's SD.h working

### ISSUE THREAD

**Issue by pavel-b-kr12** [greiman/SdFs#8]
Hi-Rali 8 GB microSDHC class 10
formatted with _SD card formatter 5_ to  fat32 or Windows to exFat
testing CardInfo.ino or other examples
SD_SCK_MHZ(4) also 16, 8 , 2 , no luck

===== got random of this 2 errors:
SD errorCode: SD_CARD_ERROR_CMD58 = 0x12
SD errorCode: SD_CARD_ERROR_ACMD41 = 0x17
with
SD errorData = 0xf
SD errorData = 0x1
itc

=====
arduino's SD.h working with SPI_FULL_SPEED, SPI_HALF_SPEED, maybe other

**Comment by greiman** [comment]
I have no Idea.  I suspect the card since CMD58 simply reads the OCR register.  The card may have poor SPI support.  Phones PCs and most other devices use the SDIO bus.

I can't help more since I don't have the card here.

**Comment by pavel-b-kr12** [comment]
Probably was voltage issue - card reader module's LDO was 3.6v. After connect to 3v3 it works good. (but I also changed cluster size to 4kb)

**Comment by greiman** [comment]
> but I also changed cluster size to 4kb

You should never format an SD with a non-standard format.  SD cards are designed with caches for FAT entries and data entries and expect structures to be the standard locations and standard sizes.  Flash and RAM buffers are designed for the standard format.  SD cards do not have 512 byte flash pages they only emulate 512 byte sectors in very large pages, much larger than your 4kb clusters.

Quote from SD Association  [formatter](https://www.sdcard.org/downloads/formatter/) page:

`In general, formatting tools provided with operating systems can format various storage media including SD/SDHC/SDXC Cards, but it may not be optimized for SD/SDHC/SDXC Cards and it may result in lower performance. `
